server:
  port: 8083
spring:
  graphql:
    graphiql:
      enable: true
  web:
    resources:
      add-mappings: true
  mail:
    host: smtp.gmail.com
    username: ala.messaoud12@gmail.com
    password: giohhbfzfkopqpmn
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
  application:
    name: ProjetSpring
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/projetweb?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
      hibename:
        format_sql: true
    show-sql: true
  security:
    user:
      username: root
      password: user

